# -*- coding: utf-8 -*-
"""McDonalds_EDA.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jSwlv2v5kVGapllCCUgQZFYkErzn6Q0D
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

file_name = list(uploaded.keys())[0]   # automatically get file name

# If CSV file
data = pd.read_csv("menu.csv")

# If Excel file (uncomment below line instead)
# data = pd.read_excel(file_name)

print(data.head())

print(data.info())
print(data.describe())

print(data.isnull().sum())

# Remove missing rows
data = data.dropna()

top_calories = data.sort_values("Calories", ascending=False).head(10)
print(top_calories[["Item", "Calories"]])

category_calories = data.groupby("Category")["Calories"].mean()
print(category_calories)

import matplotlib.pyplot as plt

top_calories.plot(x="Item", y="Calories", kind="bar")
plt.title("Top 10 Highest Calorie McDonald's Items")
plt.show()

category_calories.plot(kind="bar")
plt.title("Average Calories per Category")
plt.show()

# Low calorie items
low_cal = data.sort_values("Calories").head(10)
print("Lowest calorie items:")
print(low_cal[["Item", "Calories"]])

import seaborn as sns

corr = data.select_dtypes(include="number").corr()
sns.heatmap(corr, annot=True)
plt.title("Nutrition Correlation Heatmap")
plt.show()

